CREATE TABLE TAG(
 	WORD VARCHAR2(100) PRIMARY KEY
);

CREATE TABLE TAGLIST(
 	WORD VARCHAR2(100)PRIMARY KEY,
 	B_NUM NUMBER(5)  PRIMARY KEY

,FOREIGN KEY (WORD) REFERENCES TAG(WORD) ON DELETE CASCADE
,FOREIGN KEY (B_NUM) REFERENCES TOTAL_BOARD(b_NUM) ON DELETE CASCADE			
);



INSERT INTO


SELECT Count(recommend)
 FROM TOTAL_BOARD
 WHERE b_NUM = '10001'
  AND deleted='N';